variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

default:
  image: aldgateventuresbot/ruby-build

stages:
  - pre-build
  - build
  - release
  - publish

.license-check: &license-check |
  git clone https://${GITHUB_TOKEN}:@github.com/aldgate-ventures/license-finder.git
  source ~/.profile
  gem install bundler:1.17.3
  bundle install
  license_finder --decisions_file ./license-finder/dependency_decisions.yml

.unit-test: &unit-test |
  bundle install
  bundle exec rake test

.build: &build |
  version=$(grep 'VERSION = ' ./lib/version.rb | tr -d '"' | awk '{print $3}')
  bundle install
  gem build selfsdk.gemspec
  gem install selfsdk-${version}.gem

.git-release: &git-release |
  version=$(grep 'VERSION = ' ./lib/version.rb | tr -d '"' | awk '{print $3}')
  currentGitTag=$(git ls-remote -q --tags https://github.com/joinself/self-ruby-sdk | sort -t / -k 3 -V | grep -v '{}' | tail -n 1 | awk -F / '{print $3}')
  subject=$(git log -n 1 --format=%s)
  body=$(git log -n 1 --format=%b | grep -E '^\*|^-' | sed 's/^*/-/g') || true

  if [[ -z ${body} ]]; then
    release_notes="- ${subject}"
  else
    release_notes="${body}"
  fi

  if [[ "${version}" != "${currentGitTag}" ]]; then
    git remote set-url origin https://github.com/joinself/${CI_PROJECT_NAME}
    git tag -a ${version} -m "${version}"
    git push origin ${version}
    hub release create -m "${version}" -m "${release_notes}" ${version}
  else
    echo "Version hasn't changed. Nothing to do here."
  fi

.slack-notify: &slack-notify |
  if [[ -z ${body} ]]; then
    slack chat send "New release <https://github.com/joinself/${CI_PROJECT_NAME}|${CI_PROJECT_NAME}> <https://github.com/joinself/${CI_PROJECT_NAME}/commits/${version}|${version}>\n\n- ${subject}" '#ci'
  else
    slack chat send "New release <https://github.com/joinself/${CI_PROJECT_NAME}|${CI_PROJECT_NAME}> <https://github.com/joinself/${CI_PROJECT_NAME}/commits/${version}|${version}>\n\n${body}" '#ci'
  fi

.publish: &publish |
  version=$(grep 'VERSION = ' ./lib/version.rb | tr -d '"' | awk '{print $3}')

  if ! gem search -a selfsdk | grep $version; then
    gem push selfsdk-${version}.gem
  else
    echo "Gem version already exists. Nothing to do here."
  fi

before_script:
  - export SCRIPTS_DIR=$(mktemp -d)
  - git clone -q --depth 1 "${SCRIPTS_REPO}" "${SCRIPTS_DIR}"

license-check:
  stage: pre-build
  image: licensefinder/license_finder
  script:
    - ${SCRIPTS_DIR}/git-setup
    - *license-check
  allow_failure: true
  only:
    - branches

unit-test:
  stage: pre-build
  script:
    - *unit-test
  only:
    - branches

build:
  stage: build
  script:
    - *build
  artifacts:
    paths:
      - ./*.gem
  only:
    - branches

release:
  stage: release
  image: aldgateventuresbot/deploy
  script:
    - ${SCRIPTS_DIR}/git-setup
    - *git-release
    - *slack-notify
  only:
    - master

rubyGems:
  stage: publish
  script:
    - ${SCRIPTS_DIR}/rubygems-setup
    - *publish
  only:
    - master
