variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

default:
  image: ruby:2.6.3-stretch

stages:
  - Test
  - Build
  - Deploy

test:
  stage: Test
  script:
    - test
  only:
    - branches

build:
  stage: Build
  script:
    - build
  artifacts:
    paths:
      - ./*.gem
  only:
    - branches

rubygems:
  stage: Deploy
  script:
    - deploy
    - slackNotify
  only:
    - branches

.functions: &functions |
  set -x

  function test() {
    bundle install
    bundle exec rake test
  }

  function build() {
    local version=$(cat VERSION)
    sed -i "s/VERSION = .*/VERSION = ${version}/g" lib/version.rb
    bundle install
    gem build selfid.gemspec
    gem install selfid-${version}.gem
  }

  function deploy() {
    local version=$(cat VERSION)
    local currentGitTag=$(currentGitTag)

    echo $version
    echo $currentGitTag

    if [[ $version != $currentGitTag ]]; then
      echo "Deploying to Rubygems"
      # create & push git tag
      #sed -i "s/VERSION = .*/VERSION = ${version}/g" lib/version.rb
      #bundle install
      #gem push selfid-${version}.gem
      #
    else
      echo "Nothing to do"
    fi
  }

  function slackNotify() {
    echo "Sending Slack notification"
  }

  function currentGitTag() {
    setupGit
    local version=$(git ls-remote -q --tags https://github.com/${CI_PROJECT_PATH} | sort -t / -k 3 -V | grep -v '{}' | tail -n 1 | awk -F / '{print $3}')
    echo $version
  }

  function setupGit() {
    git config --global user.name self-ci-bot
    git config --global user.email ops@selfid.net
    git config --global url."https://${GITHUB_TOKEN}:@github.com".insteadOf "https://github.com"
  }

before_script:
  - *functions
