inherit_from:
- https://relaxed.ruby.style/rubocop.yml

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'

AllCops:
  Exclude:
    - 'selfid.gemspec'

AllCops:
  Include:
    - rubocop-rspec

Style/ClassVars:
  Enabled: false
