dist: bionic
language: ruby
rvm:
  - 2.6.3
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_install:
  - export TZ=UTC
  - curl -O http://download.selfid.net/olm/libself-olm_0.1.14_amd64.deb
  - curl -O http://download.selfid.net/omemo/libself-omemo_0.1.1_amd64.deb
  - sudo apt update
  - sudo apt install libsodium-dev
  - sudo apt install ./libself-olm_0.1.14_amd64.deb
  - sudo apt install ./libself-omemo_0.1.1_amd64.deb
  - bin/setup
script:
  - rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
