title = "gitleaks config"

[extend]

useDefault = true

[[rules]]
id = "self-key-legacy"
description = "Self Key"
regex = '''(?i)[\s'\"]+([0-9]+:[a-z0-9+\/]{43})['\"]?(\s*|$)'''

[[rules]]
id = "self-key"
description = "Self Key"
regex = '''(sk|rk)_[0-9]+:[0-9a-zA-Z+\/]{43}'''

[allowlist]
description = "global allow lists"
regexes = [
    '''(sk_)?1:56qJGhYCJmTHsYChCp3sPSjmiGlN2yG0KakYDquMAD0''',
    '''(sk_)?1:c5X4LC4EJqCN5GskpKEn+NsmqnqSjdYRtGUsbW48K2Y''',
    '''(sk_)?1:5/w2TfXvOqZIADHdSJHdgJkW+UCpoYn2IRsRliHotpc'''
]
paths = [
    '''gitleaks.toml''',
    '''(.*?)(jpg|gif|doc|pdf|bin|svg|socket)$''',
    '''Gopkg.lock'''
]
