# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acl.proto

require 'google/protobuf'

require_relative 'msgtype_pb'
require_relative 'aclcommand_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "msgproto.AccessControlList" do
    optional :type, :enum, 1, "msgproto.MsgType"
    optional :id, :string, 2
    optional :command, :enum, 3, "msgproto.ACLCommand"
    optional :payload, :bytes, 4
  end
end

module Msgproto
  AccessControlList = Google::Protobuf::DescriptorPool.generated_pool.lookup("msgproto.AccessControlList").msgclass
end
