# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgtype.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("msgtype.proto", :syntax => :proto3) do
    add_enum "msgproto.MsgType" do
      value :MSG, 0
      value :ACK, 1
      value :ERR, 2
      value :AUTH, 3
      value :ACL, 4
    end
    add_enum "msgproto.MsgSubType" do
      value :Unknown, 0
      value :AuthenticationReq, 1
      value :AuthenticationResp, 2
      value :AuthenticationQRResp, 3
      value :AuthenticationDeepLinkResp, 4
      value :FactReq, 5
      value :FactResp, 6
      value :FactQRResp, 7
      value :FactDeepLinkResp, 8
      value :EmailSecurityCodeReq, 9
      value :EmailSecurityCodeResp, 10
      value :PhoneSecurityCodeReq, 11
      value :PhoneSecurityCodeResp, 12
      value :PhoneVerificationReq, 13
      value :PhoneVerificationResp, 14
      value :EmailVerificationReq, 15
      value :EmailVerificationResp, 16
      value :DocumentVerificationReq, 17
      value :DocumentVerificationResp, 18
    end
  end
end

module Msgproto
  MsgType = Google::Protobuf::DescriptorPool.generated_pool.lookup("msgproto.MsgType").enummodule
  MsgSubType = Google::Protobuf::DescriptorPool.generated_pool.lookup("msgproto.MsgSubType").enummodule
end
