# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgtype.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("msgtype.proto", syntax: :proto3) do
    add_enum "msgproto.MsgType" do
      value :MSG, 0
      value :ACK, 1
      value :ERR, 2
      value :AUTH, 3
      value :ACL, 4
    end
  end
end

module Msgproto
  MsgType = Google::Protobuf::DescriptorPool.generated_pool.lookup("msgproto.MsgType").enummodule
end
