# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ruby

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file(".", :syntax => :proto2) do
  end
end
