module Selfid
  CLAIM_KEY_EMAIL = "email"
  CLAIM_KEY_PHONE = "phone"

  CLAIM_KEY_PASSPORT_FIRST_NAME = "passport_first_name"
  CLAIM_KEY_PASSPORT_LAST_NAME = "passport_last_name"
  CLAIM_KEY_PASSPORT_SEX = "passport_sex"
  CLAIM_KEY_PASSPORT_NUMBER = "passport_number"
  CLAIM_KEY_PASSPORT_ADDRESS = "passport_address"
  CLAIM_KEY_PASSPORT_NATIONALITY = "passport_nationality"
  CLAIM_KEY_PASSPORT_DOB = "passport_date_of_birth"
  CLAIM_KEY_PASSPORT_POB = "passport_place_of_birth"
  CLAIM_KEY_PASSPORT_EXPIRY = "passport_expiry_date"
  CLAIM_KEY_PASSPORT_ISSUE = "passport_issue_date"
  CLAIM_KEY_PASSPORT_ISSUE_AUTHORITY = "passport_issuing_authority"

  CLAIM_KEY_DRIVING_LICENSE_FIRST_NAME = "driving_license_first_name"
  CLAIM_KEY_DRIVING_LICENSE_LAST_NAME = "driving_license_last_name"
  CLAIM_KEY_DRIVING_LICENSE_SEX = "driving_license_sex"
  CLAIM_KEY_DRIVING_LICENSE_DOB = "driving_license_date_of_birth"
  CLAIM_KEY_DRIVING_LICENSE_NATIONALITY = "driving_license_nationality"
  CLAIM_KEY_DRIVING_LICENSE_NUMBER = "driving_license_number"
  CLAIM_KEY_DRIVING_LICENSE_EXPIRY = "driving_license_expiry_date"
  CLAIM_KEY_DRIVING_LICENSE_ISSUE = "driving_license_issue_date"
  CLAIM_KEY_DRIVING_LICENSE_VALID_FROM = "driving_license_valid_from"
  CLAIM_KEY_DRIVING_LICENSE_VALID_TO = "driving_license_valid_to"

  CLAIM_KEY_ID_CARD_FIRST_NAME = "id_card_first_name"
  CLAIM_KEY_ID_CARD_LAST_NAME = "id_card_last_name"
  CLAIM_KEY_ID_CARD_SEX = "id_card_sex"
  CLAIM_KEY_ID_CARD_ADDRESS = "id_card_address"
  CLAIM_KEY_ID_CARD_NATIONALITY = "id_card_nationality"
  CLAIM_KEY_ID_CARD_DOB = "id_card_date_of_birth"
  CLAIM_KEY_ID_CARD_POB = "id_card_place_of_birth"
  CLAIM_KEY_ID_CARD_NUMBER = "id_card_number"
  CLAIM_KEY_ID_CARD_EXPIRY = "id_card_expiry_date"
  CLAIM_KEY_ID_CARD_ISSUE = "id_card_issue_date"

  CLAIM_KEY_BANK_ACCOUNT_NO = "bank_account_no"
  CLAIM_KEY_BANK_FULLNAME = "bank_fullname"
  CLAIM_KEY_BANK_SORT_CODE = "bank_sort_code"
  CLAIM_KEY_BANK_NATIONALITY = "bank_nationality"
end
