name: _build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.3-buster
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Build
        shell: bash
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          apt-get update
          apt-get install -y libsodium-dev cmake build-essential
          curl -Lo /tmp/olm.deb https://download.joinself.com/olm/libself-olm_0.1.17_amd64.deb
          curl -Lo /tmp/omemo.deb https://download.joinself.com/omemo/libself-omemo_0.1.3_amd64.deb
          apt-get install -y /tmp/olm.deb /tmp/omemo.deb
          git clone https://github.com/google/flatbuffers.git /tmp/flatbuffers
          cd /tmp/flatbuffers
          git checkout v2.0.0
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          make install
          cd ${CI_WORKDIR}
          bundler_version=$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1 | sed 's/ //g')
          gem install bundler:${bundler_version}
          version=$(grep 'VERSION = ' ./lib/version.rb | tr -d '"' | awk '{print $3}')
          bundle install
          bundle exec rake test
          gem build selfsdk.gemspec
          gem install selfsdk-${version}.gem
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./*.gem
          retention-days: 1
      - name: Failure notification
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        uses: joinself/github-actions-public/failure-notification@main
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_CI_ALERTS }}
