name: _build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1.2-buster
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Build
        shell: bash
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          curl -Lo /tmp/self-omemo.deb https://github.com/joinself/self-omemo/releases/download/0.4.0/self-omemo_0.4.0_amd64.deb
          dpkg -i /tmp/self-omemo.deb
          apt-get update
          apt-get install -y cmake build-essential
          git clone https://github.com/google/flatbuffers.git /tmp/flatbuffers
          cd /tmp/flatbuffers
          git checkout v2.0.0
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          make install
          cd ${CI_WORKDIR}
          version=$(grep 'VERSION = ' ./lib/version.rb | tr -d '"' | awk '{print $3}')
          bundle install
          bundle exec rake test
          gem build selfsdk.gemspec
          gem install selfsdk-${version}.gem
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./*.gem
          retention-days: 1
      - name: Failure notification
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        uses: joinself/github-actions-public/failure-notification@main
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_CI_ALERTS }}
