name: CI

on:
  push:
    branches: [ "main" ]
  pull_requests:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test
        run: |
          apt-get update
          apt-get install -y curl libsodium-dev cmake build-essential
          curl -o /tmp/libself-olm_0.1.17_amd64.deb https://download.joinself.com/olm/libself-olm_0.1.17_amd64.deb
          curl -o /tmp/libself-omemo_0.1.3_amd64.deb https://download.joinself.com/omemo/libself-omemo_0.1.3_amd64.deb
          apt-get -y install /tmp/libself-olm_0.1.17_amd64.deb /tmp/libself-omemo_0.1.3_amd64.deb
          cd /tmp && git clone https://github.com/google/flatbuffers.git
          cd /tmp/flatbuffers && git checkout v2.0.0 && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release && make install
          bundle install
          rake test
