name: CI

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ruby:2.6.3

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: |
          apt-get update
          apt-get -y install curl libsodium-dev
          curl https://download.joinself.com/olm/libself-olm_0.1.17_amd64.deb -o /tmp/libself-olm_0.1.17_amd64.deb
          curl https://download.joinself.com/omemo/libself-omemo_0.1.3_amd64.deb -o /tmp/libself-omemo_0.1.3_amd64.deb
          curl http://archive.ubuntu.com/ubuntu/pool/universe/f/flatbuffers/libflatbuffers-dev_1.12.1~git20200711.33e2d80+dfsg1-0.6_amd64.deb -o /tmp/libflatbuffers-dev.deb
          apt-get -y install /tmp/libself-olm_0.1.17_amd64.deb
          apt-get -y install /tmp/libself-omemo_0.1.3_amd64.deb
          apt-get -y install /tmp/libflatbuffers-dev.deb

      - name: Install dependencies
        run: bundle install

      - name: Test Package
        run: rake test
