name: Docker

on:
  workflow_dispatch:

jobs:

  docker:
    name: Docker
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ghcr.io/${{ github.respository_owner }}/${{ github.event.repository.name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and publish
        run: |
          docker build -t ${IMAGE_TAG} .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ${IMAGE_TAG}
