name: _license-compliance

on:
  workflow_call:

jobs:
  license-compliance:
    runs-on: ubuntu-latest
    container:
      image: joinself/license-finder:ruby-3.1.2
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: License check
        shell: bash
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          curl -Lo /tmp/self-omemo.deb https://github.com/joinself/self-omemo/releases/download/0.4.0/self-omemo_0.4.0_amd64.deb
          dpkg -i /tmp/self-omemo.deb
          apt-get update
          apt-get install -y cmake build-essential
          git clone https://github.com/google/flatbuffers.git /tmp/flatbuffers
          cd /tmp/flatbuffers
          git checkout v2.0.0
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          make install
          cd ${CI_WORKDIR}
          gem install bundler -v 2.3.13
          bundle install
          curl -Lo /tmp/dependency_decisions.yml https://static.joinself.com/license-finder/dependency_decisions.yml
          license_finder --decisions_file /tmp/dependency_decisions.yml
      - name: Failure notification
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
        uses: joinself/github-actions-public/failure-notification@main
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_CI_ALERTS }}
